clickhouse:
  logger:
    level: information  # 生产环境使用information级别
    log: /var/log/clickhouse-server/clickhouse-server.log
    errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
    size: 1000M
    count: 10
    console: 0  # 生产环境关闭控制台输出

  http_port: 8123
  tcp_port: 9000
  max_connections: 4096
  keep_alive_timeout: 3
  max_concurrent_queries: 10  # 根据硬件配置调整，4核CPU建议10个并发

  # 缓存配置优化 - 根据16GB内存调整
  uncompressed_cache_size: 6442450944  # 6GB (16GB * 0.375)
  mark_cache_size: 3221225472  # 3GB (16GB * 0.1875)

  path: /var/lib/clickhouse/
  tmp_path: /var/lib/clickhouse/tmp/

  user_directories:
    users_xml:
      path: /etc/clickhouse-server/users.yml

  default_profile: default
  default_database: default
  timezone: Asia/Shanghai

  # 查询日志配置
  query_log:
    database: system
    table: query_log
    partition_by: toYYYYMM(event_date)
    flush_interval_milliseconds: 7500
    log_query_settings: 0  # 生产环境关闭，避免记录敏感信息
    log_query_threads: 0   # 生产环境关闭

  # 错误日志配置
  error_log:
    database: system
    table: error_log
    partition_by: toYYYYMM(event_date)
    flush_interval_milliseconds: 7500

  # 慢查询日志配置
  trace_log:
    database: system
    table: trace_log
    partition_by: toYYYYMM(event_date)
    flush_interval_milliseconds: 7500

  # 文本日志配置
  text_log:
    database: system
    table: text_log
    partition_by: toYYYYMM(event_date)
    flush_interval_milliseconds: 7500

  # 异步插入配置 - 根据4核CPU优化
  async_insert: 1
  async_insert_threads: 4  # 调整为CPU核心数

  # 合并树引擎优化 - 根据150GB存储调整
  merge_tree:
    parts_to_delay_insert: 150
    parts_to_throw_insert: 300
    max_bytes_to_merge_at_max_space_in_pool: 107374182400  # 100GB (150GB * 0.67)

  # 后台合并优化 - 根据4核CPU调整
  background_pool_size: 4  # 调整为CPU核心数
  background_schedule_pool_size: 4  # 调整为CPU核心数

  # 网络配置优化
  listen_host: 0.0.0.0
  max_server_memory_usage: 12884901888  # 12GB (16GB * 0.75)
  max_thread_pool_size: 10000

  remote_servers: {}

  include_from: /etc/clickhouse-server/config.d/*.yml