clickhouse:
  # JSON数据优化配置
  json_optimization:
    # JSON函数优化
    functions:
      # 启用JSON函数优化
      enable_json_functions: 1
      
      # JSON提取优化
      json_extract_optimization: 1
      
      # JSON路径优化
      json_path_optimization: 1

  # 查询优化 - 针对JSON数据
  query_optimization:
    # JSON查询优化器设置
    optimize_json_functions: 1
    optimize_json_extract: 1
    optimize_json_path: 1
    
    # 聚合优化 - 针对JSON聚合查询
    optimize_aggregation_in_order: 1
    optimize_aggregation_in_order_with_limit: 1
    optimize_aggregation_in_order_with_group_by: 1
    
    # 并行处理优化
    max_parallel_replicas: 1
    prefer_localhost_replica: 1
    
    # 内存优化 - 针对JSON处理
    max_memory_usage: 10737418240  # 10GB
    max_memory_usage_for_user: 8589934592  # 8GB
    max_memory_usage_for_all_queries: 10066329600  # 9.375GB

  # 存储优化 - 针对JSON数据
  storage_optimization:
    # 合并树引擎JSON优化
    merge_tree:
      # JSON数据合并优化
      parts_to_delay_insert: 150
      parts_to_throw_insert: 300
      max_bytes_to_merge_at_max_space_in_pool: 107374182400  # 100GB
      max_bytes_to_merge_at_min_space_in_pool: 53687091200  # 50GB
      
      # JSON压缩优化
      min_bytes_for_wide_part: 0
      min_rows_for_wide_part: 0
      
      # JSON索引优化
      index_granularity: 8192
      index_granularity_bytes: 0
      
      # JSON存储策略
      storage_policy: default

  # 缓存优化 - 针对JSON查询
  cache_optimization:
    # 未压缩缓存 - 用于JSON数据
    uncompressed_cache_size: 6442450944  # 6GB
    
    # 标记缓存 - 用于JSON索引
    mark_cache_size: 3221225472  # 3GB
    
    # 查询缓存 - 用于JSON查询结果
    query_cache_size: 536870912  # 512MB
    query_cache_max_entries: 10000
    
    # 字典缓存 - 用于JSON字典
    dictionary_cache_size: 536870912  # 512MB

  # 并发优化 - 针对JSON处理
  concurrency_optimization:
    # 线程池配置
    max_threads: 4  # 根据4核CPU调整
    max_insert_threads: 4
    
    # 后台任务
    background_pool_size: 4
    background_schedule_pool_size: 4
    
    # 异步插入
    async_insert: 1
    async_insert_threads: 4
    
    # 查询并发
    max_concurrent_queries: 10
    max_concurrent_queries_for_user: 5

  # 网络优化 - 针对JSON数据传输
  network_optimization:
    # 连接池
    max_connections: 4096
    keep_alive_timeout: 3
    
    # 超时设置
    connect_timeout: 10
    receive_timeout: 300
    send_timeout: 300
    
    # 请求大小限制 - 针对JSON数据
    max_request_size: 100000000  # 100MB
    max_query_size: 100000000  # 100MB

  # 监控优化 - 针对JSON查询监控
  monitoring_optimization:
    # 查询日志 - 监控JSON查询性能
    query_log:
      database: system
      table: query_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
      log_query_settings: 0  # 生产环境关闭
      log_query_threads: 0   # 生产环境关闭
    
    # 慢查询日志 - 监控JSON慢查询
    trace_log:
      database: system
      table: trace_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 系统日志
    system_log:
      database: system
      table: system_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500

  # 安全优化 - 针对JSON数据安全
  security_optimization:
    # 查询复杂度限制 - 防止JSON查询过载
    max_ast_elements: 1000000
    max_expanded_ast_elements: 1000000
    
    # 执行时间限制
    max_execution_time: 300  # 5分钟
    
    # 结果集限制
    max_result_rows: 1000000
    max_result_bytes: 1000000000  # 1GB
    
    # 读取限制
    max_read_rows: 100000000
    max_read_bytes: 1000000000  # 1GB 