clickhouse:
  # 内存配置优化 - 根据16GB内存调整
  memory:
    # 服务器总内存使用限制（建议设置为物理内存的75%）
    max_server_memory_usage: 12884901888  # 12GB (16GB * 0.75)
    
    # 查询内存限制
    max_memory_usage: 10737418240  # 10GB (16GB * 0.625)
    max_memory_usage_for_user: 8589934592  # 8GB (16GB * 0.5)
    max_memory_usage_for_all_queries: 10066329600  # 9.375GB (16GB * 0.585)
    
    # 缓存配置 - 根据16GB内存优化分配
    uncompressed_cache_size: 6442450944  # 6GB (16GB * 0.375)
    mark_cache_size: 3221225472  # 3GB (16GB * 0.1875)
    
    # 字典缓存
    dictionary_cache_size: 536870912  # 512MB (16GB * 0.03125)
    
    # 查询缓存
    query_cache_size: 536870912  # 512MB (16GB * 0.03125)
    query_cache_max_entries: 10000

  # CPU配置优化 - 根据4核CPU调整
  cpu:
    # 线程池配置
    max_threads: 4  # 根据CPU核心数调整
    max_insert_threads: 4
    max_thread_pool_size: 10000
    
    # 后台任务线程 - 根据4核CPU调整
    background_pool_size: 4
    background_schedule_pool_size: 4
    
    # 异步插入线程 - 根据4核CPU调整
    async_insert_threads: 4

  # 存储配置优化 - 根据150GB NVMe SSD调整
  storage:
    # 合并树引擎优化
    merge_tree:
      parts_to_delay_insert: 150
      parts_to_throw_insert: 300
      max_bytes_to_merge_at_max_space_in_pool: 107374182400  # 100GB (150GB * 0.67)
      max_bytes_to_merge_at_min_space_in_pool: 53687091200  # 50GB (150GB * 0.33)
      
      # 合并策略
      merge_with_ttl_timeout: 14400  # 4小时
      merge_with_recompression_ttl_timeout: 14400  # 4小时
      
      # 压缩设置 - 针对JSON数据优化
      min_bytes_for_wide_part: 0
      min_rows_for_wide_part: 0
      
      # 索引设置 - 针对JSON查询优化
      index_granularity: 8192
      index_granularity_bytes: 0
      
      # 存储策略
      storage_policy: default

    # 异步插入优化 - 根据4核CPU调整
    async_insert: 1
    async_insert_threads: 4
    wait_for_async_insert: 1

  # 网络配置优化
  network:
    # 连接池配置
    max_connections: 4096
    keep_alive_timeout: 3
    
    # 查询并发限制 - 根据4核CPU调整
    max_concurrent_queries: 10
    max_concurrent_queries_for_user: 5
    
    # 连接超时
    connect_timeout: 10
    receive_timeout: 300
    send_timeout: 300

  # 查询优化 - 针对JSON数据查询优化
  query:
    # 查询执行优化
    max_execution_time: 300  # 5分钟
    max_query_size: 100000000  # 100MB
    
    # 结果集限制
    max_result_rows: 1000000
    max_result_bytes: 1000000000  # 1GB
    
    # 读取限制
    max_read_rows: 100000000
    max_read_bytes: 1000000000  # 1GB
    
    # 查询复杂度限制
    max_ast_elements: 1000000
    max_expanded_ast_elements: 1000000
    
    # 优化器设置 - 针对JSON extract查询优化
    optimize_aggregation_in_order: 1
    optimize_aggregation_in_order_with_limit: 1
    optimize_aggregation_in_order_with_group_by: 1
    
    # 并行处理 - 根据4核CPU调整
    max_parallel_replicas: 1
    prefer_localhost_replica: 1

  # 日志配置优化
  logging:
    # 查询日志
    query_log:
      database: system
      table: query_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
      log_query_settings: 0  # 生产环境关闭
      log_query_threads: 0   # 生产环境关闭
    
    # 错误日志
    error_log:
      database: system
      table: error_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 慢查询日志
    trace_log:
      database: system
      table: trace_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 文本日志
    text_log:
      database: system
      table: text_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500

  # 系统监控
  monitoring:
    # 系统日志
    system_log:
      database: system
      table: system_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 指标收集
    metrics:
      database: system
      table: metrics
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 异步指标
    asynchronous_metrics:
      database: system
      table: asynchronous_metrics
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500 