clickhouse:
  # 网络安全配置
  networks:
    # 生产环境建议限制为特定IP段
    # 示例：只允许内网访问
    # ip: "192.168.1.0/24"
    # ip: "10.0.0.0/8"
    # 当前配置允许所有IP访问，生产环境请修改
    ip: "::/0"

  # HTTP安全配置
  http:
    # 启用HTTPS（需要SSL证书）
    # https_port: 8443
    # https_certificate: /etc/clickhouse-server/server.crt
    # https_private_key: /etc/clickhouse-server/server.key
    
    # HTTP请求限制 - 针对JSON数据优化
    max_request_size: 100000000  # 100MB
    max_uri_size: 16384  # 16KB
    
    # 启用HTTP基本认证
    # auth_type: basic
    
    # 请求超时设置
    request_timeout: 300  # 5分钟
    keep_alive_timeout: 3

  # TCP安全配置
  tcp:
    # TCP连接限制
    max_connections: 4096
    keep_alive_timeout: 3
    
    # 启用SSL/TLS（需要证书）
    # tcp_port_secure: 9440
    # tcp_certificate: /etc/clickhouse-server/server.crt
    # tcp_private_key: /etc/clickhouse-server/server.key

  # 查询安全配置 - 针对JSON数据查询优化
  query:
    # 查询长度限制
    max_query_size: 100000000  # 100MB
    
    # 查询复杂度限制 - 针对JSON extract查询优化
    max_ast_elements: 1000000
    max_expanded_ast_elements: 1000000
    
    # 查询执行时间限制
    max_execution_time: 300  # 5分钟
    
    # 结果集限制
    max_result_rows: 1000000
    max_result_bytes: 1000000000  # 1GB
    
    # 读取限制
    max_read_rows: 100000000
    max_read_bytes: 1000000000  # 1GB

  # 系统安全配置
  system:
    # 禁用危险函数
    # 注意：这些设置可能会影响某些功能
    # enable_optimize_predicate_expression: 0
    # enable_optimize_aggregation_in_order: 0
    
    # 限制系统表访问
    # readonly: 0  # 设置为1可限制某些系统表访问
    
    # JSON数据安全设置
    # 限制JSON函数的使用
    # enable_optimize_aggregation_in_order: 1  # 启用聚合优化
    # enable_optimize_aggregation_in_order_with_limit: 1
    # enable_optimize_aggregation_in_order_with_group_by: 1

  # 日志安全配置
  logger:
    # 不记录敏感信息 - 生产环境安全设置
    log_query_settings: 0  # 生产环境建议关闭
    log_query_threads: 0   # 生产环境建议关闭
    
    # 日志轮转
    size: 1000M
    count: 10
    
    # 日志级别
    level: information  # 生产环境使用information级别

  # 备份安全配置
  backup:
    # 备份文件权限
    # backup_file_permissions: 0600
    
    # 备份目录权限
    # backup_directory_permissions: 0700

  # 监控安全配置
  monitoring:
    # 启用系统监控
    system_log:
      database: system
      table: system_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 启用指标收集
    metrics:
      database: system
      table: metrics
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500
    
    # 慢查询监控 - 针对JSON查询优化
    trace_log:
      database: system
      table: trace_log
      partition_by: toYYYYMM(event_date)
      flush_interval_milliseconds: 7500 