services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.6-alpine
    container_name: clickhouse-server
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=default
    volumes:
      - ./clickhouse/config/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse/config/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client -u default --password clickhouse123 --query 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
